### ISSUE TITLE
nextcordでスラッシュに移行

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#113]
~~もうしっかりと動きそうなので早めに移行してほとんどのコマンドをスラッシュに対応させたい。~~
~~追記：Pycordの2.0が正式にリリースされたらほとんどのコマンドをスラッシュに移行したい。~~
追記：nextcordに変更 そしてもうすぐ正式リリースのため予め移行作業をslashブランチで済ませることにする。

**Comment by tasuren** [comment]
> もうしっかりと動きそうなので早めに移行してほとんどのコマンドをスラッシュに対応させたい。

前言撤回、コグ未対応っぽいから2.0が正式リリースされたら。

**Comment by tasuren** [comment]
> あ、ちなみに登録制限あるからね 50までしか作れないからそのことを考慮してね

Yeah
だからグループコマンド作りまくる
サーバーツールカテゴリーなら`tool`みたいなグループコマンド作る。

**Comment by waki285** [comment]
> あ、ちなみに登録制限あるからね 50までしか作れないからそのことを考慮してね

100だけど
![image](https://user-images.githubusercontent.com/67305123/144340503-530cea5a-a30d-4b91-8a0c-6ca93c7d0871.png)

**Comment by tasuren** [comment]
あ、そうだったんだ。

**Comment by tuna2134** [comment]
かわったんだ

**Comment by waki285** [comment]
変わったというか実装当時からこうだったはずなんだけど...

**Comment by tasuren** [comment]
いつでも対応できるようにした。

**Comment by tuna2134** [comment]
もうやったから消していい気がする

**Comment by tasuren** [comment]
そういやそうだった。
