### ISSUE TITLE
全体的なクールダウンの追加

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#144]
スパムなどによる意図的な負荷を受けた際のためにコマンド以外の機能にも全体的にクールダウンを付ける。
また、コマンド以外でクールダウンを簡単に付けるためのものを作る。

* [x] クールダウンの簡単に付ける方法の考案をする。
* [ ] クールダウンを簡単に付けるためのものの開発をする。
    * [ ] 管理用のコグを作る。
    * [ ] 登録用のものを作る。
* [ ] 実装する。

**Comment by tuna2134** [comment]
process_commandってもう置いてある？

**Comment by tuna2134** [comment]
大体
@bot.event
async def on_message(message):
        if bot.is_command(message):
            time = time()
            if time - data[message.author.id] > 4
                  await bot.process_command(message)
                  data[message.author.id] = time
                  
で良くね？

**Comment by tuna2134** [comment]
ベースはこれでやっていって
あとはクールダウン中の人のみ一回だけ送信した後また実行したら無視するとか

**Comment by tuna2134** [comment]
あとコマンドを使えなくする(ブラックリスト的な)機能とか

**Comment by tasuren** [comment]
あ、いやそういうのじゃなくて、クールダウンが追加されてないやつとかコマンドじゃない機能とかのクールダウンね。

**Comment by tasuren** [comment]
それを実装するライブラリ作る。

**Comment by yaakiyu** [comment]
そういやd.pyにはすでにcog単位でそういうことができる機能があったんだったな

**Comment by tuna2134** [comment]
そうなん？
