### ISSUE TITLE
アナウンスチャンネルの自動公開

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#156]
これは設定する系かな。あったら便利だね。
公開出来たら一定時間リアクションを付けるとか。
公開に失敗したらバツのリアクションつけて理由(公開しすぎ、権限がなかったなど)をDMに送るとか。

**Comment by tasuren** [comment]
DMSくんがPullRequest出してくれたからこれはもう実装済み。

**Comment by yaakiyu** [comment]
ok
