### ISSUE TITLE
Spotify再生に対応 (できるかわからない)

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#166]
Spotifyって確か一瞬しか曲を流せなかったんじゃなかったかな...
イントロクイズボットで使われてた記憶
でも一応提案。

**Comment by tasuren** [comment]
一応ライブラリがあるからそれ使うか。
最悪ライブラリは僕が作る。

**Comment by tasuren** [comment]
#104 と被っているのでclose
