### ISSUE TITLE
注意報・警報速報機能

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#169]
災害情報全般かな。
それぞれ別のAPIからとってくることになりそうな予感。

**Comment by tasuren** [comment]
地震のを作る予定。
P2P使えばいい。

**Comment by tasuren** [comment]
めんどくさいな
もう地震だけでええんちゃう(

**Comment by kazuma11121125** [comment]
気象庁xml使えば防災情報系全部いける。まぁ僕の知り合いの機能と被るようなことはしてほしくないけど。
地震はp2p地震情報のやつを使うのをおすすめします。
