### ISSUE TITLE
メモ機能

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#172]
単純。まさに単純。
ユーザーごとに保存でいいんじゃないかな。
内容は一応txtのみ、2000文字までで

**Comment by tasuren** [comment]
そこらへんにいるBotのDMを使うとかじゃダメなんかな。

**Comment by yaakiyu** [comment]
知らんけど、
別サーバーで「rt!memo view ○○」ってやるだけで他の人と共有できるとかそういう利点からだと思う

**Comment by tasuren** [comment]
ほ、ほほう。
グループDMじゃだめなのk(

**Comment by tasuren** [comment]
> ほ、ほほう。
> 
> グループDMじゃだめなのk(

グループDMで良さそうなので消臭
