### ISSUE TITLE
SBAN機能

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#181]
題名通り、2つのサーバーでBANされた人を同期する。

同期設定の条件：
①RTが両方のサーバーに入っていて、その両方でメンバーをBANする権限を持っていること
②両方のサーバーでそれぞれ管理者権限を持っている人(かぶっていたら1人だけでよし)の了承があること

同期方法：
- コマンド設定時にコマンドを実行したサーバー**が**同期対象サーバーのBANリストに合わせる
- BANメンバー追加時・削除時(これはどちらのサーバーでも)にもう片方と同期。
- 一応RTが落ちている間にBANされた可能性を考えてon(_full?)_ready時にBANされた人があっているか確認

GBANせずとも「このサーバーでBANしてるからこっちでも自動でBANしてほしい！」っていうニーズに答える。
(ちなみに：これは僕が触ったことのあるbotでは一度も見たことのない機能だからdiscord初なんじゃないかな。)

**Comment by tasuren** [comment]
@yaakiyu 
これSBANにする？

**Comment by yaakiyu** [comment]
いいんじゃないかな
SBANもGlobalChatみたいにいくつかのグループを作れるようにしたら?

**Comment by tasuren** [comment]
うーん、めんどうさいな。
あとこのissueをsbanに改名して欲しい。
