### ISSUE TITLE
RT's SDKを作る。

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#190]
要は簡単な開発キットで、今の状態だと環境を整えるのがめんどくさいのでコントリビュートしずらい。

**Comment by tuna2134** [comment]
fmm

**Comment by tuna2134** [comment]
出来るっちゃ出来るけど
MySQLとかの関係で難しそう

**Comment by tasuren** [comment]
> 出来るっちゃ出来るけど
> 
> MySQLとかの関係で難しそう

実行時に`aiosqlite`に置き換えればいい。

**Comment by tuna2134** [comment]
aiosqlite3がいいんじゃない？

**Comment by tuna2134** [comment]
websocketのもんだいもあるけど

**Comment by tasuren** [comment]
> aiosqlite3がいいんじゃない？

aiosqliteにする。
スター数がこっちの方が多いから。
(仕組みもあんま変わりはない。)

**Comment by tasuren** [comment]
> websocketのもんだいもあるけど

バックエンドも実行するようにする。
