### ISSUE TITLE
ボットの起動を速くする

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#198]

**Comment by tasuren** [comment]
できない。

**Comment by tuna2134** [comment]
標準ライブラリのpickle使えばちょっとは速くなる

**Comment by tuna2134** [comment]
諦めんな！
諦めたら終わり！

**Comment by tasuren** [comment]
うーん、情報が古くなって信頼できない情報になるからやりたくない。

**Comment by tasuren** [comment]
特権インテントだいぶ申請したからそれ通るまで待ってる。

**Comment by tasuren** [comment]
> ひでえ Classのデータとかをpickle使えば保存できる

I know
> うーん、情報が古くなって信頼できない情報になるからやりたくない。

↑

**Comment by tuna2134** [comment]
古いか？
普通に人工知能とかでは使うよ

**Comment by tasuren** [comment]
常に最新にしておかないと何かしら不具合が発生するかもしれない。

**Comment by tuna2134** [comment]
そうかな？
一分間に一回更新するやり方でいいんじゃね？
もしもエラーが起きたら、更新で、その後からは一分間に一回更新でいい気がする

**Comment by tasuren** [comment]
> 常に最新にしておかないと何かしら不具合が発生するかもしれない。

**Comment by tuna2134** [comment]
あと他にもあるような気がする
