### ISSUE TITLE
ipをホワイトリスト化

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#210]
つまりdiscord apiのホワイトリストに登録してもらう

**Comment by tasuren** [comment]
そんなんしてくれるの？

**Comment by tuna2134** [comment]
> そんなんしてくれるの？

Yes
大手のボットは登録してもらっている

**Comment by tuna2134** [comment]
レートリミットも回避できる

**Comment by tuna2134** [comment]
だけどサーバー数制限とかありそうだと思うけど
大丈夫でしょ

**Comment by tasuren** [comment]
wtf
やるとしたら英語もっとサポートしてもっとサーバー数増えてDisboardみたいなサーバー掲示板完成したらにするわ。

**Comment by tuna2134** [comment]
> wtf
> やるとしたら英語もっとサポートしてもっとサーバー数増えてDisboardみたいなサーバー掲示板完成したらにするわ。

でももうそろそろやらんとapiリミットにひっかりやすくなるよ

**Comment by tuna2134** [comment]
https://support.discord.com/hc/en-us/community/posts/360042409852-API-Applications-having-IP-whitelist

**Comment by tuna2134** [comment]
あミスった

**Comment by tuna2134** [comment]
どこだっけ？

**Comment by tuna2134** [comment]
大手が少なすぎて、情報が少ない

**Comment by tuna2134** [comment]
だけどdiscordに問い合わせればやってもらえるはず

**Comment by tuna2134** [comment]
> 

サポートするのは手伝うけど、RT-TEAMに参加したい()

**Comment by tasuren** [comment]
いつかその時が来たらまた考えるから今はclose
