### ISSUE TITLE
RTbotに昔あった、星がついたら、いいね通知するやつ

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#215]

**Comment by tuna2134** [comment]
廃止された理由は忘れた

**Comment by tasuren** [comment]
> 廃止された理由は忘れた

別にいらないとかだった気がする。

**Comment by tuna2134** [comment]
そうだっけ？

**Comment by tasuren** [comment]
> そうだっけ？

君はこの機能が欲しいの？

**Comment by tuna2134** [comment]
うん

**Comment by yaakiyu** [comment]
スターボード機能か、某Cbotを蹴ることができるようになるから僕はいると思う

**Comment by tasuren** [comment]
> スターボード機能か、某Cbotを蹴ることができるようになるから僕はいると思う

スターボードはもうある。
多分DMSくんが言いたいのは❤️リアクションをつけたらその人に通知がいくっていう昔あった機能のことだと思う。

**Comment by tuna2134** [comment]
Yes

**Comment by yaakiyu** [comment]
なる
gooddm機能だったかな

**Comment by tasuren** [comment]
> なる
> gooddm機能だったかな

よく覚えてるな。

**Comment by tuna2134** [comment]
Yeah
記憶力がいいからね
