### ISSUE TITLE
ダッシュボードのコンバーター追加

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#218]

**Comment by tasuren** [comment]
追加済み。
実行はコマンドフレームワークでメッセージコマンドとまんま同じように実行されるから。

**Comment by tuna2134** [comment]
コンバーターはdiscord.pyのextにある
@bot.command()
async def cmd(ctx, user:discord.User):
    pass
これのdiscord.Userでコマンド実行するとIDやメンションをdiscord.Userとして出してくれる。
つまりもしもdiscord.Userやdiscord.Roleだったらロールのリストとかを表示する

**Comment by tuna2134** [comment]
こういうこと

**Comment by tasuren** [comment]
それも実装ずみ。
`Union`とかはめんどくさいから非対応になってる。
