### ISSUE TITLE
自動返信機能で複数のワードに同時に反応する

### ISSUE THREAD

**Issue by Nemu627** [RT-Team/rt-bot#225]
自動返信機能でワードを複数登録していて、送信されたメッセージの中に登録された２つ以上のワードが入っていた場合に二つの処理を同時に返すようにしていただきたいです。

rt!cmd set googlefan on ぐーぐれふあん>>>Ok
rt!cmd set nyan on にゃぁぁぁぁぁあああああん！>>>Ok
音夢「googlefanとnyan、どっちが強いだろう」
RT「ぐーぐれふあん」「にゃぁぁぁぁぁあああああん！」

現段階だと50音順で早いワードのみにしか反応しません。
よろしくお願いします。

**Comment by tuna2134** [comment]
僕はいいと思う

**Comment by tasuren** [comment]
Ohk
最大三個までなら返信するようにするかも。

**Comment by Nemu627** [comment]
そうですね。悪用される懸念も減るので。
よろしくお願いします。

**Comment by tasuren** [comment]
実装した。
