### ISSUE TITLE
Captcha認証で勝手にタイムアウトする問題

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#226]

**Comment by tasuren** [comment]
タイムアウト設定でキックするようにしている場合は、キックは認証済みロールを持っていない場合のみされる。
だからbotに認証済みロールを付けるとかすればいい。

**Comment by tasuren** [comment]
思ったけどbotも認証する必要ない気がした。
てことでRTサーバーにて投票中

**Comment by tasuren** [comment]
Botは認証対象にならないようにした。
