### ISSUE TITLE
rtaのランキング機能を実装

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#244]

**Comment by tuna2134** [comment]
俺が担当者！？

**Comment by tasuren** [comment]
この機能を作ったのは君だからとりあえず付けといた。

**Comment by tuna2134** [comment]
> この機能を作ったのは君だからとりあえず付けといた。

ふむ
まあユーザー追加は作っといた

**Comment by tuna2134** [comment]
https://github.com/RT-Team/rt-bot/pull/252
ここでとりあえずつくっているえ
