### ISSUE TITLE
スクリーンショットに電話の表示を追加する

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-bot#246]
まあiPhone 13でいいと思うけど。

- [x] playwrightのインストール
- [ ] playwrightのセットアップ
- [x] playwrightのwebkitを使う

**Comment by tuna2134** [comment]
セットアップはplaywright installでできる

**Comment by tuna2134** [comment]
https://github.com/RT-Team/rt-bot/pull/247

**Comment by tasuren** [comment]
playwrightってNode.js動かすんだよね？

**Comment by tuna2134** [comment]
前言撤回
やっぱいらない

**Comment by tuna2134** [comment]
@tasuren
いらないよ

**Comment by tasuren** [comment]
ちょっとまってて
wip

**Comment by tuna2134** [comment]
> ちょっとまってて
> wip

Ok
