### ISSUE TITLE
Ticketコマンドで作成したTicketボタンを押してチャンネル作成後、もう一度Ticketボタンを押すと作ったチャンネルが削除される

### ISSUE THREAD

**Issue by LZMAShili** [RT-Team/rt-bot#254]
Ticketコマンドでパネルを作成
作成したTicketボタンを押してチャンネル作成
もう一度Ticketボタンを押すと、その人が作ったチャンネルが削除される

RTACに送られたアーカイブも削除されるため、実用に耐えられない。

**Comment by tuna2134** [comment]
いやそう言うものですから

**Comment by tasuren** [comment]
いや、アーカイブしたやつも削除されるのは問題

**Comment by tuna2134** [comment]
ああね

**Comment by tuna2134** [comment]
> いや、アーカイブしたやつも削除されるのは問題

アーカイブとかってあったっけ？

**Comment by LZMAShili** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98644057/156145324-fd660124-dc68-4070-93ec-1fa7f282a843.png">

**Comment by tasuren** [comment]
あるよ、RTACっていうカテゴリーを作ったら使える。  
> ヘルプしっかり見よう

...

**Comment by tuna2134** [comment]
> 

これコマンドじゃなくてボタンにした方が良くね？

**Comment by tuna2134** [comment]
> 

あとcloseとかじゃなくてアーカイブコマンドとかも用意すべきなのでは？

**Comment by tasuren** [comment]
書き直し予定

**Comment by tuna2134** [comment]
> 使い勝手悪いから書き直し予定

ちょっとそこだけ修正するわ

**Comment by LZMAShili** [comment]
現状作ってアーカイブしてもう一度Ticketボタンを押した結果(carlBotにログを出してもらってる、こちらが手動で削除したわけではない。)
<img width="602" alt="image" src="https://user-images.githubusercontent.com/98644057/156146004-1ca69b2b-3655-49d7-9aa6-42c65461a275.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/98644057/156146070-20ec7586-8697-493d-8a64-8f2533d7bb2f.png">

**Comment by tuna2134** [comment]
fmm

**Comment by tuna2134** [comment]
> 現状作ってアーカイブしてもう一度Ticketボタンを押した結果(carlBotにログを出してもらってる、こちらが手動で削除したわけではない。)
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/98644057/156146004-1ca69b2b-3655-49d7-9aa6-42c65461a275.png">
> <img alt="image" width="343" src="https://user-images.githubusercontent.com/98644057/156146070-20ec7586-8697-493d-8a64-8f2533d7bb2f.png">

rt!close実行したら削除されるん？

**Comment by LZMAShili** [comment]
rt!closeの時点ではチャンネルがRTACへの移動が実行される。
もう一度Ticketボタンを押すと、その人が作った-rtチケットが削除される。

**Comment by LZMAShili** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/98644057/156146775-4720dfe9-81ca-4e5f-a706-2218fd902cde.png">
このログを見てもらったらわかりやすいかな(一連の流れ)

**Comment by tuna2134** [comment]
なるほどね

**Comment by tuna2134** [comment]
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/98644057/156146775-4720dfe9-81ca-4e5f-a706-2218fd902cde.png">
> 
> このログを見てもらったらわかりやすいかな(一連の流れ)

書き直した方が早そう。。。

**Comment by tuna2134** [comment]
@tasuren チケットのやつ俺書き直したい

**Comment by tasuren** [comment]
うーん、どのようなものが出来上がるかによる。  
どのようなものをどのように作るのかを教えてくれればいいよ。

**Comment by tuna2134** [comment]
> 

えーとね
ボタンでチケット作るやん
でチケットにクローズボタンとアーカイブボタンをついたボタンを送信して、ピン留めする。
あと同じようなやつをコマンドでやれるようにもする

**Comment by tasuren** [comment]
なるほど、チケット機能書き直しはそうするかもしれません。  
チケットパネルのボタンからチケット作成 -> チケットチャンネル -> チケット管理コマンドで削除,アーカイブが可能  
もしすでにチケットが存在する場合はそのチケットのチャンネルのリンクを表示する。

**Comment by tuna2134** [comment]
> なるほど、チケット機能書き直しはそうするかもしれません。
> チケットパネルのボタンからチケット作成 -> チケットチャンネル -> チケット管理コマンドで削除,アーカイブが可能
> もしすでにチケットが存在する場合はそのチケットのチャンネルのリンクを表示する。

管理コマンドは不便だと思うけど。。。
コマンドよりボタンでのクリックした方がいい

**Comment by tasuren** [comment]
管理コマンドでボタンがついたメッセージがでないとは僕は言っていない。  
僕が考えているのは管理コマンドで管理パネルがでるまたは最近追加されたモーダルがでてくるとかにする予定

**Comment by tasuren** [comment]
ピン留めか
じゃあそうするか

**Comment by tuna2134** [comment]
あとjsonファイルとかで会話の内容を保存して、それを復元させるとか

**Comment by tuna2134** [comment]
あるよ

**Comment by tasuren** [comment]
@LZMAShili アーカイブ(RTAC)を有効にしている場合は削除しないで新しくチケットを作るようにした。

**Comment by tuna2134** [comment]
> あとjsonファイルとかで会話の内容を保存して、それを復元させるとか

こう言うのがあったら良さそうなんだよね

**Comment by minato37103710** [comment]
@tuna2134 チャンネル削除しないならその機能要らんくね

**Comment by tuna2134** [comment]
> > あとjsonファイルとかで会話の内容を保存して、それを復元させるとか
> 
> こう言うのがあったら良さそうなんだよね

なんか便利だと思う

**Comment by LZMAShili** [comment]
> @LZMAShili アーカイブ(RTAC)を有効にしている場合は削除しないで新しくチケットを作るようにした。

助かります！

**Comment by tuna2134** [comment]
おお

**Comment by tuna2134** [comment]
おお

**Comment by LZMAShili** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/98644057/156153836-35e827f9-d890-4500-8ed2-cf79b8884fc5.png">
クールダウンの時間がだんだん増えていく(0秒とは逆の方向へカウントされていく)のは仕様ですか？

**Comment by tuna2134** [comment]
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/98644057/156153836-35e827f9-d890-4500-8ed2-cf79b8884fc5.png">
> 
> クールダウンの時間がだんだん増えていく(0秒とは逆の方向へカウントされていく)のは仕様ですか？

多分

**Comment by tuna2134** [comment]
えーとね負荷対策とか荒らし対策なのでは？

**Comment by LZMAShili** [comment]
これは120秒待ってくださいから0秒へと近づいていくのではなく、
0秒から120秒に近づいていくのが正しいのですね。

**Comment by yaakiyu** [comment]
いや多分計算間違ってます

**Comment by yaakiyu** [comment]
tasurenがいつか大幅な書き換えをする時まで我慢していただければ...
まぁこんぐらいなら治すけど、どうせなら全部一から作り直したほうが楽だと思うし

**Comment by LZMAShili** [comment]
了解しました。
まあ連続してチケットを作成することはそうそうない(実害がほとんどない)ので、気長にお待ちしておきます。
カウントダウンではなくストップウォッチですとサーバー利用者に周知すれば問題ないので。
