### ISSUE TITLE
RTの現状書き直し予定(by tasuren)

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#256]
* [ ] Ticket
* [ ] 通貨機能(#240)
* [x] userinfo(#278)
* [ ] 6ch
* [ ] MineSweeper
* [ ] poll
* [ ] グローバルチャット

**Comment by tasuren** [comment]
読み上げは書き直した。
あと`* [ ] poll`みたいにやって欲しい。
そしたら以下みたいになるから。
* [ ] poll

**Comment by yaakiyu** [comment]
なるほど

**Comment by LZMAShili** [comment]
チケットを利用した際、DMに来るクールタイムの秒数がカウントダウンではなくストップウォッチになっている点の修正もお願いします。

**Comment by tasuren** [comment]
@yaakiyu 
グローバルチャットも追加しておいて欲しい。

**Comment by yaakiyu** [comment]
ok
