### ISSUE TITLE
discord.pyへの帰還

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#260]
開発再開したので。

**Comment by tasuren** [comment]
discord.pyもスラッシュにコマンドフレームワークを対応させなければ。

**Comment by tasuren** [comment]
作業は`slash`ブランチで行うことにする。
それとスラッシュ対応させるライブラリを作る予定なのでそれを使う。

**Comment by yaakiyu** [comment]
それならイベントをクールダウンさせるって計画を組み込んで
モンキーパッチ軍書き直しすれば?

**Comment by yaakiyu** [comment]
あとrtlibとrtutilの合体とかも

**Comment by tasuren** [comment]
> それならイベントをクールダウンさせるって計画を組み込んで
> 
> モンキーパッチ軍書き直しすれば?

イベントクールダウンとかそれは別にする。
僕がそれをするためのライブラリ作る予定だから。

**Comment by yaakiyu** [comment]
なるほどね
