### ISSUE TITLE
GBANリストをjson形式で公開

### ISSUE THREAD

**Issue by kazuma11121125** [RT-Team/rt-bot#264]
他のBOTでもRTbotのGBANリストに入っているユーザーをBANできるようになるため、効果が上がると思う。(誰かが言ってた記憶)

**Comment by kazuma11121125** [comment]
リクエストすれば取得できるような感じ

**Comment by tasuren** [comment]
APIを作るということか。
`RT-Team/rt-backend`の方にこのissue立てといて欲しい。

**Comment by kazuma11121125** [comment]
sorry
