### ISSUE TITLE
ログ機能強化（編集したメッセージのbefore afterの通知）

### ISSUE THREAD

**Issue by LZMAShili** [RT-Team/rt-bot#265]
<img width="135" alt="image" src="https://user-images.githubusercontent.com/98644057/157451694-5398af62-f3a1-4288-b901-c44121fc18ee.png">
こういうのがほしい

**Comment by tasuren** [comment]
了解

**Comment by tuna2134** [comment]
@tasuren マージ頼んだ

**Comment by tasuren** [comment]
merged
