### ISSUE TITLE
[チケット] 機能追加要望

### ISSUE THREAD

**Issue by Xeltica** [RT-Team/rt-bot#266]
いくつかチケットに関する機能追加がほしいな…と感じたのでお願いします。
* チャンネル名を作成者ではなくチケット名にできるようにしてほしい
* チケットの初期メッセージをチケット作成時に設定できるようにしてほしい
* チケットのボタンをカスタマイズできるようにしてほしい

**Comment by tasuren** [comment]
#256 恐らくこれの書き直しで実装します。
