### ISSUE TITLE
RT 機能提案 一覧

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#54]
```py
1.N+M人に指定したN個のロールをランダムに付与する(人狼とかで使えそう)
2.rt!ngで設定したNGワードを〇〇のロールがついてる人だけ発言可能
3.gameコマンドのgif対応
4.embedでメニューﾒｯｾｰｼﾞ
5.ピン留めでembedを使う
6.翻訳リアクションの例外設定機能(wとかにも反応するから)
7.募集機能を常にチャンネルの下に設定する(無理ゲー感)
8.匿名投票
9.メニューでembed使用
10.検索結果を上から何個か並べる
11.チケット削除を作成したチャンネル内で
12.asp(チャンネルトピックのやつの)をメッセージにも
13.hydra(音楽bot)的なひとつの専用チャンネルに操作パネルを置く音楽機能
14.スターボード画像対応
15.rt!ng listのやつをhelp形式にする
16.グローバルチャットの発言一日以内なら削除できる機能
17.ディス速upカウンター
18.画像認証はDMに画像を送られるように(許可してなかった場合の対応含む)
19.helpコマンドのetcとetc2をまとめる
20.
  ①引用したいメッセージにリアクション
  ②引用元への返信をそのチャンネルに送信
  ③いつもの引用みたいなのが出現
21.rt!funp list とかで自分の投稿した画像見れるように
22.雨雲レーダー
23.アナウンスチャンネルの自動公開
24.ストップウォッチ(カウントダウンじゃなくて、開始、終了指定しての)
25.cpicの認証文字をアルファベッド+字をくねくねさせる
26.チャンネル権限をコマンドで変更できるようにする機能
27.みんなの辞書
28.ゲーム機能
29.super-global-chatに接続
30.バグ修正(画像認証で一回入ってもう一回入ったときに認証したらキックされてしまうバグ、このチャンネル含めPIN動作しないバグ、DMでhelpをうつとこうなるバグ(語彙力はない)、絶対ン止めプラグイン)
31.全ての機能のON OFF機能
32.雨雲レーダー
33.地震情報
34.注意報・警報速報機能
35.交通情報機能
36.***バグ改善***
37.アナウンスチャンネルの自動公開(あるっけ)
38.過疎化通知
39.時計(ストップウォッチ カウントダウンなども含む)
40.音楽や読み上げのコマンドできる音量調節(なんか聞いたことある気が)
41.複数のテキストチャンネルの読み上げ
42.音楽検索して音楽流す機能
43.電卓
44.メモ機能
45.リマインダー機能
46.指定のTwitterやYouTubeの通知
47.受験生応援機能(頑張れ)
48.logをもの凄く細かく
49.一括ロール指定(そのロールがついてる人にDM送信やkick みんなから消去 一括追加 ランダム追加などなど)
50.宣伝防止機能(ON OFF機能付き)
51.バグ発生のリアルタイム機能
52.あるbotがダウンしたときの通知機能
53.誰から招待されて入ったかのlog機能
54.指定したサイトの通信障害通知機能
55.スタンプをグローバルチャットに対応
56.テキストファイルのページ化
57.vcから自動で抜ける
58.オンラインランキング(だれが一番オンライン時間が長いか)
59.ピン留めのやつ、ピン留めした1番最近のものが設定される
60.プリフェクス変更機能
61.エラーログ
62.Spotify再生に対応
63.Googleアシスタント(無理ならAlexa)
64.マーダーミステリー(殺人ゲーム)
65.絶対ピン止メッセージ、footerに説明を付ける
66.現在のcpuの状況をみんなが見れる機能
67.アナウンスチャンネルでの自動フォロー機能
``` 旧機能提案よりコピペ

**Comment by tasuren** [comment]
作れないものと既にあるやつを削除した。

* N+M人に指定したN個のロールをランダムに付与する(人狼とかで使えそう)
* rt!ngで設定したNGワードを〇〇のロールがついてる人だけ発言可能
* gameコマンドのgif対応
* 募集機能を常にチャンネルの下に設定する(無理ゲー感)
* 匿名投票
* hydra(音楽bot)的なひとつの専用チャンネルに操作パネルを置く音楽機能
* スターボード画像対応
* helpコマンドのetcとetc2をまとめる
* rt!funp list とかで自分の投稿した画像見れるように
* 雨雲レーダー ＜ーこれはパクリにならないよね
* アナウンスチャンネルの自動公開
* ストップウォッチ(カウントダウンじゃなくて、開始、終了指定しての)
* チャンネル権限をコマンドで変更できるようにする機能
* みんなの辞書
* super-global-chatに接続 (やるかわからん)
* 地震情報
* 注意報・警報速報機能
* 交通情報機能
* 過疎化通知
* 時計(ストップウォッチ カウントダウンなども含む)
* 音楽や読み上げのコマンドできる音量調節(なんか聞いたことある気が)
* 音楽検索して音楽流す機能
* 電卓
* メモ機能
* リマインダー機能
* 受験生応援機能(頑張れ)
* 宣伝防止機能(ON OFF機能付き)
* バグ発生のリアルタイム機能
* あるbotがダウンしたときの通知機能
* 指定したサイトの通信障害通知機能
* スタンプをグローバルチャットに対応
* ピン留めのやつ、ピン留めした1番最近のものが設定される
* プリフェクス変更機能
* エラーログ
* Spotify再生に対応 (できるかわからない)
* マーダーミステリー(殺人ゲーム)
* 現在のcpuの状況をみんなが見れる機能

**Comment by yaakiyu** [comment]
ここの存在わすれてないよね～^^
- 現在のcpuの状況をみんなが見れる機能
- スターボード画像対応
- プリフェクス変更機能
- 匿名投票
- 宣伝防止機能(ON OFF機能付き)
- スタンプをグローバルチャットに対応
- アナウンスチャンネルの自動公開
- チャンネル権限をコマンドで変更できるようにする機能
- gameコマンドのgif対応
- 過疎化通知
- 時計(ストップウォッチ, タイマー, リマインダー)
- super-global-chatに接続 (やるかわからん)
- rt!funp list とかで自分の投稿した画像見れるように
- hydra(音楽bot)的なひとつの専用チャンネルに操作パネルを置く音楽機能
- 雨雲レーダー
- 地震情報
- Spotify再生に対応 (できるかわからない)
- ピン留めのやつ、ピン留めした1番最近のものが設定される
- 受験生応援機能(頑張れ)
- 注意報・警報速報機能
- チャンネル権限をコマンドで変更できるようにする機能
- 音楽や読み上げのコマンドできる音量調節(なんか聞いたことある気が)
- 交通情報機能
- メモ機能
- リマインダー機能
- N+M人に指定したN個のロールをランダムに付与する(人狼とかで使えそう)
- rt!ngで設定したNGワードを〇〇のロールがついてる人だけ発言可能
- 募集機能を常にチャンネルの下に設定する(無理ゲー感)
- みんなの辞書
- 電卓
- マーダーミステリー(殺人ゲーム)

いくつか削除して、簡単に作れそう&需要のあるであろう順番に並べかえてみた

**Comment by yaakiyu** [comment]
すべて登録したのでclose。
