### ISSUE TITLE
プレミアム機能

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#75]
プレイリストやロールリンカーなど設定できる数が決まってるやつでもっと使えるようになったりするやつ。

**Comment by tuna2134** [comment]
いるのそれ？

**Comment by tuna2134** [comment]
普通にクレジットカードとか経由で支払うんだろ？
たぶん審査が・・・
絶望すぎる

**Comment by tuna2134** [comment]
無料の方がいいし
まずアンケートした方が良いと思う

**Comment by tuna2134** [comment]
あ
こういうのとかいいんじゃね？
https://pay.jp

**Comment by yaakiyu** [comment]
# RT課金要素
**月額500円 RT Pro**
* RTサブ機(音楽プレイヤー, 読み上げ, 申請式擬似専属Bot)
  (R2, R3, R4, R5)
* 優先問い合わせ対応
* 数制限全機能倍増

**その他**
* 数制限倍増 一つにつき月額10円
* 優先問い合わせ対応 僕にコーヒーを送る

(by tasuren)

**Comment by yaakiyu** [comment]
# サブスク課金予定
基本的に三つのプラン
```md
# 一般
## 月額10円 RTer
ただの募金、応援ありがとう！
## 月額50円 RTer Pro
ほぼすべての機能数制限二倍になる。
例：音楽プレイヤーのプレイリストに入れれる曲の最大が800から1600になる。
サーバー掲示板のDisboardでいうBumpの間隔が2/3になる。
## 月額100円 RTer VIP
サーバー掲示板のDisboardでいうBumpの間隔が1/3になる。
機能数制限が三倍になる。
下のサーバー掲示板の広告枠一つ無料でゲットできる。

# 番外
## サーバー掲示板の広告枠 (月額30円)
広告としてサーバーを表示するようにすることが可能になる。
(Help画面, サーバー掲示板の隅等)
```

**Comment by tasuren** [comment]
その二つの予定マージするかどっちか捨てたい。
どうしようかな。

**Comment by tuna2134** [comment]
fm,
