### ISSUE TITLE
rtrole機能関連の提案

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-bot#87]
・いくつかのロールを指定できるように(引数にそのまま指定したときはandで、別々のコマンドで指定したときはorで分岐できる)
・なんのロールが足りないか出してほしい

**Comment by tasuren** [comment]
> いくつかのロールを指定できるように(引数にそのまま指定したときはandで、別々のコマンドで指定したときはorで分岐できる)

これはもうできるからOK。

**Comment by yaakiyu** [comment]
もうできるんだ
